%%% analytical conjugate problem


a=(1/A0)^(1/4)*(cos(pi/8)-1i*sin(pi/8));
I=1i;
C1=(-exp((-1 - I)*a)*I + exp((1 - I)*a) - 3*I*exp((1 + I)*a) - exp((-1 + I)*a) - ...
    (1 + I)*exp(2*I*a) - 2*I + (1 - I)*exp(2*a))/(a*(4 + exp((1 + I)*a) + ...
    exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a))*(((2*exp((1 + I)*a) + 1) - I) + (1 + I)*exp(2*a)));
C2=(((exp((1 - I)*a) + (-1 + I)*exp((2 + 2*I)*a)...
    + 2*I*exp(2*a) + 3*I*exp((1 + I)*a) + exp((3 - I)*a)*I + 1) + I) ...
    - exp((3 + I)*a))/((((2*exp((1 + I)*a) + 1) - I) + ...
    (1 + I)*exp(2*a))*a*(4 + exp((1 + I)*a) + exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a)));

C3=(exp((-1 - I)*a)*I - exp((3 - I)*a)*I - (2 + 2*I)*exp(2*a)...
    - 4*cos(a)*exp(a) - 2 + 2*I)/((((2*exp((1 + I)*a) + 1) - I) ...
    + (1 + I)*exp(2*a))*a*(4 + exp((1 + I)*a) + exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a)));
C4=((1 + I)*exp((-1 + I)*a) + 2 +...
    (1 - I)*exp((1 + I)*a))/(2*(4 + exp((1 + I)*a) ...
    + exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a))*a);

y=C1*exp(a*x)+C2*exp(-a*x)+C3*exp(I*a*x)+C4*exp(-I*a*x);

b=(1/A0)^(1/4)*(cos(pi/8)+1i*sin(pi/8));

A = [1,1,1,1;...
    1,-1,1i,-1i;...
    exp(b),exp(-b),-exp(1i*b),-exp(-1i*b);...
    exp(b),-exp(-b),-1i*exp(1i*b),1i*exp(-1i*b)];

B=[a/2*(C1-C2+1i*C3-1i*C4); a^2/2/b*(C1+C2-C3-C4); a^3/2/b^2*(C1*exp(a)-C2*exp(-a)-1i*C3*exp(1i*a)+1i*C4*exp(-1i*a));...
    (a^4/2+1i/2/A0)/b^3*(C1*exp(a)+C2*exp(-a)+C3*exp(I*a)+C4*exp(-I*a))];

V=A\B;

g=V(1)*exp(b*x)+V(2)*exp(-b*x)+V(3)*exp(I*b*x)+V(4)*exp(-I*b*x)-...
    a/2*(C1*exp(a*x)-C2*exp(-a*x)+C3*I*exp(I*a*x)-C4*I*exp(-I*a*x));

d2g = b^2*(V(1)*exp(b*x)+V(2)*exp(-b*x)-V(3)*exp(I*b*x)-V(4)*exp(-I*b*x)) -...
    a^3/2*(C1*exp(a*x)-C2*exp(-a*x)-I*C3*exp(I*a*x)+I*C4*exp(-I*a*x));

dy=C1*a*exp(a*x)-C2*a*exp(-a*x)+C3*a*I*exp(I*a*x)-C4*a*I*exp(-I*a*x);
d2y = a^2*(C1*exp(a*x)+C2*exp(-a*x)-C3*exp(I*a*x)-C4*exp(-I*a*x));
d3y=a^3*(C1*exp(a*x)-C2*exp(-a*x)-I*C3*exp(I*a*x)+I*C4*exp(-I*a*x));

F_prop =  -(-dy(1)*A0*conj(d3y(1))-conj(dy(1))*A0*d3y(1) + A0*d2y(1)*conj(d2y(1)))/4;

dFdA = d2y.*conj(d2g)+conj(d2y).*d2g;

