%%% analytical

a=(1/A0)^(1/4)*(cos(pi/8)-1i*sin(pi/8));
I=1i;
C1=(-exp((-1 - I)*a)*I + exp((1 - I)*a) - 3*I*exp((1 + I)*a) - exp((-1 + I)*a) - ...
    (1 + I)*exp(2*I*a) - 2*I + (1 - I)*exp(2*a))/(a*(4 + exp((1 + I)*a) + ...
    exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a))*(((2*exp((1 + I)*a) + 1) - I) + (1 + I)*exp(2*a)));
C2=(((exp((1 - I)*a) + (-1 + I)*exp((2 + 2*I)*a)...
    + 2*I*exp(2*a) + 3*I*exp((1 + I)*a) + exp((3 - I)*a)*I + 1) + I) ...
    - exp((3 + I)*a))/((((2*exp((1 + I)*a) + 1) - I) + ...
    (1 + I)*exp(2*a))*a*(4 + exp((1 + I)*a) + exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a)));

C3=(exp((-1 - I)*a)*I - exp((3 - I)*a)*I - (2 + 2*I)*exp(2*a)...
    - 4*cos(a)*exp(a) - 2 + 2*I)/((((2*exp((1 + I)*a) + 1) - I) ...
    + (1 + I)*exp(2*a))*a*(4 + exp((1 + I)*a) + exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a)));
C4=((1 + I)*exp((-1 + I)*a) + 2 +...
    (1 - I)*exp((1 + I)*a))/(2*(4 + exp((1 + I)*a) ...
    + exp((1 - I)*a) + exp((-1 + I)*a) + exp((-1 - I)*a))*a);

y=C1*exp(a*x)+C2*exp(-a*x)+C3*exp(I*a*x)+C4*exp(-I*a*x);
